package com.exam.model;
// Generated Apr 4, 2019 7:50:54 PM by Hibernate Tools 4.3.1

import com.exam.modelDao.AddvDao;
import com.exam.modelDao.MemberDao;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import org.primefaces.PrimeFaces;

/**
 * Addv generated by hbm2java
 */
@ManagedBean(name = "add")
@SessionScoped
public class Addv implements java.io.Serializable {

    private List<Addv> list2 = new ArrayList<>();
    private Integer id;
    private String addtype;
    private String descr;
    private String loc;
    private String ttl;
    private String cont;
    private String imgname;
    private String url;
    private String date;

    public Addv() {
    }

    public Addv(String addtype, String descr, String loc, String ttl, String cont, String imgname, String url, String date) {
        this.addtype = addtype;
        this.descr = descr;
        this.loc = loc;
        this.ttl = ttl;
        this.cont = cont;
        this.imgname = imgname;
        this.url = url;
        this.date = date;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

 
    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public String getLoc() {
        return this.loc;
    }

    public void setLoc(String loc) {
        this.loc = loc;
    }

    public String getTtl() {
        return this.ttl;
    }

    public void setTtl(String ttl) {
        this.ttl = ttl;
    }

    public String getCont() {
        return this.cont;
    }

    public void setCont(String cont) {
        this.cont = cont;
    }

    public String getImgname() {
        return this.imgname;
    }

    public void setImgname(String imgname) {
        this.imgname = imgname;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public List<Addv> getList2() {
        AddvDao ad = new AddvDao();
        list2 = ad.addData();
        return list2;
    }

    public void setList2(List<Addv> list2) {
        this.list2 = list2;
    }

    public String doSend() {
        AddvDao md = new AddvDao();
        md.saveData(this);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "DATA SAVED", "SUCCESSFULLY ADDED A NEW RECORD");
        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "adminPanel";
    }

        public String doSendByMember() {
        AddvDao md = new AddvDao();
        md.saveData(this);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "PAYMENT REQUIRED", "YOU NEED TO PAY \n\t BEFORE FINAL ADDBMISSION");
        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "paymentPanel";
    }     
            
    

    public String doUpdate() {
        AddvDao md = new AddvDao();
        md.updateData(this);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "UPDATED", "DATA UPDATED SUCCESSFULLY");
        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "adminPanel";
    }

    public String doDelete() {
        AddvDao md = new AddvDao();
        md.deleteData(this);

        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "DELETED", "DELETED SUCCESSFULLY.");

        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "adminPanel";

    }

    public String getAddtype() {
        return addtype;
    }

    public void setAddtype(String addtype) {
        this.addtype = addtype;
    }

}
