package com.exam.model;
// Generated Apr 4, 2019 7:50:54 PM by Hibernate Tools 4.3.1

import com.exam.modelDao.MemberDao;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import org.primefaces.PrimeFaces;

/**
 * Member generated by hbm2java
 */
@ManagedBean(name = "mem")
@SessionScoped
public class Member implements java.io.Serializable {

    private List<Member> list1 = new ArrayList<>();

    private Integer id;
    private String name;
    private String email;
    private String gender;
    private String pass;
    private String cont;

    public Member() {
    }

    public Member(String name, String email, String gender, String pass, String cont) {
        this.name = name;
        this.email = email;
        this.gender = gender;
        this.pass = pass;
        this.cont = cont;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getPass() {
        return this.pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public String getCont() {
        return this.cont;
    }

    public void setCont(String cont) {
        this.cont = cont;
    }

    public List<Member> getList1() {
        MemberDao md = new MemberDao();
        list1 = md.memberData();
        return list1;
    }

    public void setList1(List<Member> list1) {
        this.list1 = list1;
    }

    public String doSend() {
        MemberDao md = new MemberDao();
        md.saveData(this);
        md.saveData(this);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "DATA SAVED", "SUCCESSFULLY ADDED A NEW RECORD");
        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "adminPanel";
    }

    public String doUpdate() {
        MemberDao md = new MemberDao();
        md.updateData(this);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "UPDATED", "DATA UPDATED SUCCESSFULLY");
        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "adminPanel";
    }

    public String doDelete() {
        MemberDao md = new MemberDao();
        md.deleteData(this);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "DELETED", "DELETED SUCCESSFULLY.");
        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "adminPanel";

    }
    
        public String loginMember(){
        String ret = "";
        MemberDao ad = new MemberDao();
        
        if (ad.aMember(name, pass)!=null) {
           
            ret="memberPanel";
        }else {
            FacesContext context = FacesContext.getCurrentInstance();
         
       
            ret = "memberLogin";
             context.addMessage(null, new FacesMessage("Successful",  "Your message: ") );
        context.addMessage(null, new FacesMessage("Second Message", "Additional Message Detail"));
        }
        return ret;
        
    }

}
