package com.exam.model;
// Generated Apr 4, 2019 7:50:54 PM by Hibernate Tools 4.3.1

import com.exam.modelDao.AddvDao;
import com.exam.modelDao.PaymentDao;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import org.primefaces.PrimeFaces;

/**
 * Payment generated by hbm2java
 */
@ManagedBean(name = "pay")
@SessionScoped
public class Payment implements java.io.Serializable {

    private List<Payment> list3 = new ArrayList<>();
    private int id;
    private String addname;
    private String addtype;
    private String amount;
    private String paytype;
    private String date;

    public Payment() {
    }

    public Payment(int id) {
        this.id = id;
    }

    public Payment(int id, String addname, String addtype, String amount, String paytype, String date) {
        this.id = id;
        this.addname = addname;
        this.addtype = addtype;
        this.amount = amount;
        this.paytype = paytype;
        this.date = date;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getAddname() {
        return this.addname;
    }

    public void setAddname(String addname) {
        this.addname = addname;
    }

    public String getAddtype() {
        return this.addtype;
    }

    public void setAddtype(String addtype) {
        this.addtype = addtype;
    }

    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getPaytype() {
        return this.paytype;
    }

    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }

    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public List<Payment> getList3() {
        PaymentDao pd = new PaymentDao();
        list3 = pd.paymentData();
        return list3;
    }

    public void setList3(List<Payment> list3) {
        this.list3 = list3;
    }

    public String doSend() {
        PaymentDao md = new PaymentDao();
        md.saveData(this);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "DATA SAVED", "SUCCESSFULLY ADDED A NEW RECORD");
        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "adminPanel";
    }
    
             public String doSendByMember() {
        PaymentDao md = new PaymentDao();
        md.saveData(this);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "THANKS FOR PAYING", "YOUR ADD WILL UPLOADED SOON");
        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "memberPanel";
    }

    public String doUpdate() {
        PaymentDao md = new PaymentDao();
        md.updateData(this);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "UPDATED", "DATA UPDATED SUCCESSFULLY");
        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "adminPanel";
    }

    public String doDelete() {
        PaymentDao md = new PaymentDao();
        md.deleteData(this);
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "DELETED", "DELETED SUCCESSFULLY.");
        PrimeFaces.current().dialog().showMessageDynamic(message);
        return "adminPanel";

    }
}
