package com.exam.model;
// Generated Apr 4, 2019 7:50:54 PM by Hibernate Tools 4.3.1



/**
 * Shopadd generated by hbm2java
 */
public class Shopadd  implements java.io.Serializable {


     private Integer id;
     private String addtype;
     private String descr;
     private String loc;
     private String cont;
     private String image;
     private String date;

    public Shopadd() {
    }

    public Shopadd(String addtype, String descr, String loc, String cont, String image, String date) {
       this.addtype = addtype;
       this.descr = descr;
       this.loc = loc;
       this.cont = cont;
       this.image = image;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAddtype() {
        return this.addtype;
    }
    
    public void setAddtype(String addtype) {
        this.addtype = addtype;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }
    public String getCont() {
        return this.cont;
    }
    
    public void setCont(String cont) {
        this.cont = cont;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


